///////////////////////////////////////////////////////////
//  Employe.cs
//  Implementation of the Class Employe
//  Generated by Enterprise Architect
//  Created on:      20-janv.-2023 09:48:58
//  Original author: GRognone
///////////////////////////////////////////////////////////




public class Employe : Personne {

	private string typeDeContrat;
	private DateTime dateDEmbauche;
	private string Service;
	private string posteOccupe;
	private int Quotité;
	private Salaire sonSalaire;
	private JourDeConges sesJoursDeConges;

	public Employe(){

	}

	~Employe(){

	}

	public override void Dispose(){

	}

}//end Employe