///////////////////////////////////////////////////////////
//  Personne.cs
//  Implementation of the Class Personne
//  Generated by Enterprise Architect
//  Created on:      20-janv.-2023 09:48:56
//  Original author: GRognone
///////////////////////////////////////////////////////////




public class Personne {

	private string nom;
	private string prenom;
	private Date dateDeNaissance;

	public Personne(){

	}

	~Personne(){

	}

	public virtual void Dispose(){

	}

}//end Personne