///////////////////////////////////////////////////////////
//  Salaire.cs
//  Implementation of the Class Salaire
//  Generated by Enterprise Architect
//  Created on:      20-janv.-2023 09:48:59
//  Original author: GRognone
///////////////////////////////////////////////////////////




public class Salaire {

	private float salaireBrut;
	private float chargesPatronales;
	private float chargesSalariales;

	public Salaire(){

	}

	~Salaire(){

	}

	public virtual void Dispose(){

	}

	public float CalculerSalaireCharge(){

		return 0;
	}

	public float CalculerSalaireNet(){

		return 0;
	}

	public void CalculerSalaire(){

	}

}//end Salaire