// <auto-generated />
using System;
using BankTransactions.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankTransactions.DataBase.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20230515100433_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankTransactions.Models.BankTransaction", b =>
                {
                    b.Property<int>("Transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transaction_Id"));

                    b.Property<decimal>("Transaction_Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("transaction_amount");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_Date");

                    b.Property<long>("Transaction_From")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_from");

                    b.Property<long>("Transaction_To")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_to");

                    b.HasKey("Transaction_Id");

                    b.ToTable("bank_transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
