DROP TABLE CHATS;
DROP TABLE RACES;

CREATE TABLE RACES
(
	ID INT PRIMARY KEY,
	Race VARCHAR(20) NOT NULL UNIQUE

);



CREATE TABLE CHATS
(
	Numero_Puce BIGINT PRIMARY KEY NOT NULL,
	Nom varchar(25),
	Age int,
	Race INTEGER NOT NULL DEFAULT 2 CONSTRAINT FK_RACES FOREIGN KEY (Race) REFERENCES RACES(ID)
);