// <auto-generated />
using System;
using ApiBankTransactionDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiBankTransactionDb.Migrations
{
    [DbContext(typeof(BankTransactionDbContext))]
    [Migration("20230512063920_version1")]
    partial class version1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiBankTransactionModels.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Transaction Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Transaction Date");

                    b.Property<double>("TransactionAmount")
                        .HasColumnType("float")
                        .HasColumnName("Transaction Amount");

                    b.Property<long>("TransactionFrom")
                        .HasMaxLength(11)
                        .HasColumnType("bigint")
                        .HasColumnName("Transaction From");

                    b.Property<long>("TransactionTo")
                        .HasMaxLength(11)
                        .HasColumnType("bigint")
                        .HasColumnName("Transaction To");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
